# Example configuration with Simple Memory
system:
  architecture: arm64
  num_cpus: 2
  num_slcs: 2
  clock: 2.6GHz
  sve_vl: 256
  cache_line_size: 64
  cpus:
  - simple
  - o3cpu

cpus:
  simple:
    model: AtomicSimple
    clock: 2.6GHz
  o3cpu: !include cpu.yaml

caches: !include caches.yaml

memory:
  regions:
    - model: Simple
      channels: 2
      size: 1GB
      bandwidth: "60GiB/s"
      latency: "5ns"

interconnect:
  model: classic

network: !include network.yaml

simulation:
  gem5_version: 24.1.0.2
  full_system: True
