default_plots = [
        dict(
            suffix = "mesh_flit_{name}_vnet{vnet}",
            col_regex = r"mesh_flit_{name}_hist_vnet{vnet}_b(\d+)",
            name = 'network_latency',
            vnet = 0,
            max_x   = 50,
            x_label = 'VNET={vnet} Total Network Latency [Cycles]',
            y_label = 'Events',
        ),
        dict(
            suffix = "mesh_flit_{name}_vnet{vnet}",
            col_regex = r"mesh_flit_{name}_hist_vnet{vnet}_b(\d+)",
            name = 'network_latency',
            vnet = 1,
            max_x   = 50,
            x_label = 'VNET={vnet} Total Network Latency [Cycles]',
            y_label = 'Events',
        ),
        dict(
            suffix = "mesh_flit_{name}_vnet{vnet}",
            col_regex = r"mesh_flit_{name}_hist_vnet{vnet}_b(\d+)",
            name = 'network_latency',
            vnet = 2,
            max_x   = 50,
            x_label = 'VNET={vnet} Total Network Latency [Cycles]',
            y_label = 'Events',
        ),
        dict(
            suffix = "mesh_flit_{name}_vnet{vnet}",
            col_regex = r"mesh_flit_{name}_hist_vnet{vnet}_b(\d+)",
            name = 'network_latency',
            vnet = 3,
            max_x   = 50,
            min_x = 5,
            x_label = 'VNET={vnet} Total Network Latency [Cycles]',
            y_label = 'Events',
        ),
        dict(
            suffix = "mesh_flit_{name}_vnet{vnet}",
            col_regex = r"mesh_flit_{name}_hist_vnet{vnet}_b(\d+)",
            name = 'queueing_latency',
            vnet = 0,
            max_x   = 50,
            x_label = 'VNET={vnet} Total Queueing Latency [Cycles]',
            y_label = 'Events',
        ),
        dict(
            suffix = "mesh_flit_{name}_vnet{vnet}",
            col_regex = r"mesh_flit_{name}_hist_vnet{vnet}_b(\d+)",
            name = 'queueing_latency',
            vnet = 1,
            max_x   = 50,
            x_label = 'VNET={vnet} Total Queueing Latency [Cycles]',
            y_label = 'Events',
        ),
        dict(
            suffix = "mesh_flit_{name}_vnet{vnet}",
            col_regex = r"mesh_flit_{name}_hist_vnet{vnet}_b(\d+)",
            name = 'queueing_latency',
            vnet = 2,
            max_x   = 50,
            x_label = 'VNET={vnet} Total Queueing Latency [Cycles]',
            y_label = 'Events',
        ),
        dict(
            suffix = "mesh_flit_{name}_vnet{vnet}",
            col_regex = r"mesh_flit_{name}_hist_vnet{vnet}_b(\d+)",
            name = 'queueing_latency',
            vnet = 3,
            max_x   = 50,
            x_label = 'VNET={vnet} Total Queueing Latency [Cycles]',
            y_label = 'Events',
        ),
]