# NeoverseN1 configuration for SE
# Based on the O3_ARM_Neoverse_N1.py configuration by Bine Brank
# https://github.com/binebrank/gem5/blob/neoverse_model/configs/common/cores/arm/O3_ARM_Neoverse_N1.py
simulation:
  gem5_version: 24.1.0.3
  full_system: False

system:
  architecture: arm64
  num_cpus: 1
  num_slcs: 1
  clock: 2.6GHz
  sve_vl: 256
  cache_line_size: 64
  cpus:
  - o3cpu

cpus:
  o3cpu: !include cpu.yaml

caches: !include caches.yaml

memory:
  regions:
    - model: DRAM
      channels: 4
      size:  2GiB
      dram_settings: !include ../memory/DDR4_2400_16x4.yaml

interconnect:
  model: classic
  classic:
    slcs_per_core: 1

