model: Arm
clock: 2.6GHz
bpred:
  model: BiMode
  settings:
    globalPredictorSize: 8192
    globalCtrBits: 2
    choicePredictorSize: 8192
    choiceCtrBits: 2
  BTB:
    numEntries: 4096
    tagBits: 16
    instShiftAmt: 2

FU:
  Branch:
    count: 2
    ops:
      - [Branch, 1]

  Int_Single:
    count: 3
    ops:
      - [IntAlu, 1]

  Int_Complex:
    count: 1
    ops:
      - [IntAlu, 1]
      - [IntMult, 2]
      - [IntDiv, 9, false]
      - [IprAccess, 1]

  FP_SIMD:
    count: 2
    ops:
      - [FloatAdd, 2]
      - [FloatCmp, 2]
      - [FloatCvt, 3]
      - [FloatMisc, 3]
      - [FloatMult, 3]
      - [FloatMultAcc, 4]
      - [FloatDiv, 11, false]
      - [FloatSqrt, 12, false]
      - [SimdAdd, 2]
      - [SimdAddAcc, 4]
      - [SimdAlu, 2]
      - [SimdCmp, 2]
      - [SimdCvt, 3]
      - [SimdMisc, 2]
      - [SimdMult, 4]
      - [SimdMultAcc, 4]
      - [SimdShift, 2]
      - [SimdShiftAcc, 4]
      - [SimdDiv, 9, false]
      - [SimdSqrt, 9]
      - [SimdFloatAdd, 2]
      - [SimdFloatAlu, 2]
      - [SimdFloatCmp, 2]
      - [SimdFloatCvt, 3]
      - [SimdFloatDiv, 11, false]
      - [SimdFloatMisc, 2]
      - [SimdFloatMult, 4]
      - [SimdFloatMultAcc, 4]
      - [SimdFloatMatMultAcc, 4]
      - [SimdFloatSqrt, 12, false]
      - [SimdReduceAdd, 4]
      - [SimdReduceAlu, 6]
      - [SimdReduceCmp, 5]
      - [SimdFloatReduceAdd, 4, false]
      - [SimdFloatReduceCmp, 5]
      - [SimdExt]
      - [SimdFloatExt]
      - [SimdConfig]
      - [SimdAes]
      - [SimdAesMix]
      - [SimdSha1Hash]
      - [SimdSha1Hash2]
      - [SimdSha256Hash]
      - [SimdSha256Hash2]
      - [SimdShaSigma2]
      - [SimdShaSigma3]

  LoadStore:
    count: 2
    ops:
      - [MemRead]
      - [MemWrite]
      - [FloatMemRead]
      - [FloatMemWrite]

  PredALU:
    count: 1
    ops:
      - [SimdPredAlu]

  Matrix_Unit:
    count: 1
    ops:
      - [Matrix]
      - [MatrixMov]
      - [MatrixOP]

core:
  fetchToDecodeDelay: 1
  decodeToFetchDelay: 1
  decodeToRenameDelay: 1
  renameToDecodeDelay: 1
  renameToFetchDelay: 1
  renameToIEWDelay: 1
  renameToROBDelay: 1
  iewToCommitDelay: 1
  iewToDecodeDelay: 1
  iewToFetchDelay: 1
  iewToRenameDelay: 1
  issueToExecuteDelay: 1
  commitToDecodeDelay: 1
  commitToFetchDelay: 1
  commitToIEWDelay: 1
  commitToRenameDelay: 1

  fetchWidth: 4
  decodeWidth: 4
  renameWidth: 8
  dispatchWidth: 8
  issueWidth: 8
  wbWidth: 8
  commitWidth: 8
  squashWidth: 8

  numRobs: 1
  numROBEntries: 128
  numIQEntries: 120
  LQEntries: 68
  SQEntries: 72

  LSQDepCheckShift: 0
  LSQCheckLoads: true
  store_set_clear_period: 250000

  LFSTSize: 1024
  SSITSize: 1024

  cacheLoadPorts: 200
  cacheStorePorts: 200

  fetchBufferSize: 64
  fetchQueueSize: 64

  fetchTrapLatency: 1
  trapLatency: 13

  backComSize: 32
  forwardComSize: 32

  numPhysIntRegs: 120
  numPhysFloatRegs: 128
  # numPhysIntRegs * 5
  numPhysVecRegs: 128
  numPhysVecPredRegs: 64
  numPhysMatRegs: 2
  numPhysCCRegs: 1280

  needsTSO: false

