model: Arm
clock: 2.6GHz
bp: BiMode
FU:
  FP:
    count: 1
    ops:
      - [FloatAdd, 2]
      - [FloatCmp, 2]
      - [FloatCvt, 3]
      - [FloatMisc, 3]
      - [FloatMult, 3]
      - [FloatMultAcc, 4]
      - [FloatDiv, 11, false]
      - [FloatSqrt, 12, false]
  Load:
    count: 1
    ops:
      - [MemRead]
      - [FloatMemRead]
  Store:
    count: 1
    ops:
      - [MemWrite]
      - [FloatMemWrite]
  Single_Int:
    count: 1
    ops:
      - [IntAlu, 1]
  Multi_Int:
    count: 1
    ops:
      - [IntAlu, 1]
      - [IntMult, 2]
      - [IntDiv, 9, false]
      - [IprAccess, 1]
  PredALU:
    count: 2
    ops:
      - [SimdPredAlu]
  SIMD_FP:
    count: 1
    ops:
      - [SimdAdd, 2]
      - [SimdAddAcc, 4]
      - [SimdAlu, 2]
      - [SimdCmp, 2]
      - [SimdCvt, 3]
      - [SimdMisc, 2]
      - [SimdMult, 4]
      - [SimdMultAcc, 4]
      - [SimdShift, 2]
      - [SimdShiftAcc, 4]
      - [SimdDiv, 9, false]
      - [SimdSqrt, 9, false]
      - [SimdFloatAdd, 2]
      - [SimdFloatAlu, 2]
      - [SimdFloatCmp, 2]
      - [SimdFloatCvt, 3]
      - [SimdFloatMisc, 2]
      - [SimdFloatMult, 4]
      - [SimdFloatMultAcc, 4]
      - [SimdFloatDiv, 11, false]
      - [SimdFloatSqrt, 12, false]
      - [SimdReduceAdd, 10]
      - [SimdReduceAlu, 12]
      - [SimdReduceCmp, 9]
      - [SimdFloatReduceAdd, 8, false]
      - [SimdFloatReduceCmp, 9]
      - [FloatAdd, 2]
      - [FloatCmp, 2]
      - [FloatCvt, 3]
      - [FloatMisc, 3]
      - [FloatMult, 3]
      - [FloatMultAcc, 4]
      - [FloatDiv, 11, false]
      - [FloatSqrt, 12, false]

core:
  LFSTSize: 1024
  LQEntries: 128
  LSQDepCheckShift: 0
  SQEntries: 128
  SSITSize: 1024
  backComSize: 32
  cacheLoadPorts: 200
  cacheStorePorts: 200
  commitToDecodeDelay: 1
  commitToFetchDelay: 1
  commitToIEWDelay: 1
  commitToRenameDelay: 1
  commitWidth: 8
  decodeToFetchDelay: 1
  decodeToRenameDelay: 1
  decodeWidth: 8
  dispatchWidth: 8
  fetchBufferSize: 64
  fetchQueueSize: 64
  fetchToDecodeDelay: 1
  fetchTrapLatency: 1
  fetchWidth: 8
  forwardComSize: 32
  iewToCommitDelay: 1
  iewToDecodeDelay: 1
  iewToFetchDelay: 1
  iewToRenameDelay: 1
  issueToExecuteDelay: 1
  issueWidth: 8
  numIQEntries: 128
  numPhysFloatRegs: 256
  numPhysIntRegs: 256
  # numPhysIntRegs * 5
  numPhysCCRegs: 1280
  numPhysMatRegs: 2
  numPhysVecPredRegs: 64
  numPhysVecRegs: 364
  numROBEntries: 512
  renameToDecodeDelay: 1
  renameToFetchDelay: 1
  renameToIEWDelay: 1
  renameToROBDelay: 1
  renameWidth: 8
  squashWidth: 8
  trapLatency: 13
  wbWidth: 8
