#!/bin/bash

# PKG
PKG_NAME="walberla"
PKG_GIT="https://i10git.cs.fau.de/walberla/walberla.git"
PKG_VER="v4.1"

git -C $SRCDIR clone --depth 1 --branch $PKG_VER $PKG_GIT

for P in *.patch; do
    patch -d $SRCDIR/$PKG_NAME -p1 < $P
done

cmake -B $BLDDIR/$PKG_NAME $SRCDIR/$PKG_NAME -DCMAKE_VERBOSE_MAKEFILE:BOOL=TRUE -DWALBERLA_BUILD_BENCHMARKS:BOOL=ON  -DWALBERLA_BUILD_TESTS:BOOL=OFF -DWALBERLA_BUILD_TOOLS:BOOL=OFF -DWALBERLA_BUILD_TUTORIALS:BOOL=OFF  -DWALBERLA_BUILD_SHOWCASES:BOOL=OFF  -DWALBERLA_BUILD_DOC:BOOL=OFF -DWALBERLA_BUILD_WITH_GPROF:BOOL=OFF -DWALBERLA_BUILD_WITH_MPI:BOOL=OFF -DWALBERLA_BUILD_WITH_OPENMP:BOOL=ON -DBUILD_TESTING:BOOL=OFF -DWALBERLA_USE_M5:BOOL=ON

make  -C $BLDDIR/$PKG_NAME -j$(nproc)

install -D -m 0755 -t $BENCHD/$PKG_NAME/bin $BLDDIR/$PKG_NAME/apps/benchmarks/UniformGrid/UniformGridBenchmark-m5

cmake -B $BLDDIR/$PKG_NAME $SRCDIR/$PKG_NAME -DCMAKE_VERBOSE_MAKEFILE:BOOL=TRUE -DWALBERLA_BUILD_BENCHMARKS:BOOL=ON  -DWALBERLA_BUILD_TESTS:BOOL=OFF -DWALBERLA_BUILD_TOOLS:BOOL=OFF -DWALBERLA_BUILD_TUTORIALS:BOOL=OFF  -DWALBERLA_BUILD_SHOWCASES:BOOL=OFF  -DWALBERLA_BUILD_DOC:BOOL=OFF -DWALBERLA_BUILD_WITH_GPROF:BOOL=OFF -DWALBERLA_BUILD_WITH_MPI:BOOL=OFF -DWALBERLA_BUILD_WITH_OPENMP:BOOL=ON -DBUILD_TESTING:BOOL=OFF -DWALBERLA_USE_M5:BOOL=OFF

make  -C $BLDDIR/$PKG_NAME -j$(nproc)

install -D -m 0755 -t $BENCHD/$PKG_NAME/bin $BLDDIR/$PKG_NAME/apps/benchmarks/UniformGrid/UniformGridBenchmark


install -D -m 0644 -t $BENCHD/$PKG_NAME/data n01-x30y30z30.dat


