L1I:
  size: 64KiB
  assoc: 4
  latency:
    tag: 1
    data: 1
  classic:
    mshrs: 16
    tgts_per_mshr: 16
    writeback_clean: False
  prefetcher:
    model: Stride
    settings:
      degree: 2

L1D:
  size: 64KiB
  assoc: 4
  latency: 
    tag: 1
    data: 1
  classic:
    mshrs: 16
    tgts_per_mshr: 16
    writeback_clean: False
  prefetcher:
    model: Tagged
    settings:
      degree: 2

L2:
  size: 1MiB
  assoc: 8
  latency:
    tag: 1
    data: 4
    response: 4
  classic:
    mshrs: 32
    tgts_per_mshr: 16
    writeback_clean: True
    clusivity: mostly_incl
    xbar_width: 64
  prefetcher:
    model: Tagged
    settings:
      degree: 8

SLC:
  size: 2MiB
  assoc: 16
  system_shared: Yes
  latency: 
    tag: 1
    data: 10
    response: 10
  classic:
    mshrs: 96
    tgts_per_mshr: 16
    clusivity: mostly_excl
    xbar_width: 64
    snoop_filter_max_capacity: "8MiB"

IWC:
  size: 8KiB
  assoc: 4
  latency: 
    tag: 1
    data: 1
    response: 1
  classic:
    mshrs: 20
    tgts_per_mshr: 12
    write_buffers: 16
    writeback_clean: True

DWC:
  size: 8KiB
  assoc: 4
  latency: 
    tag: 1
    data: 1
    response: 1
  classic:
    mshrs: 20
    tgts_per_mshr: 12
    write_buffers: 16
    writeback_clean: True

CoherentIO:
  size: 1kB
  assoc: 8
  latency: 
    tag: 50
    data: 50
    response: 50
  classic:
    mshrs: 20
    tgts_per_mshr: 12
