
time_plots = [
    dict(
        suffix = "cycles",
        desc = 'Time-to-solution in Cycles',
        x_label = 'TTS [cycles]',
        value_col = 'cycles',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "time",
        desc = 'Time-to-solution in Seconds',
        x_label = 'TTS [s]',
        value_col = 'time',
        bar_label = "{:.2E}",
    ),
]
# CPU
cpu_plots = [

    dict(
        suffix = "instructions_per_cycle",
        desc = 'Instructions/cycle',
        x_label = 'Instructions/cycle',
        value_col = 'CommittedInsts_cycle',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix = "flops_per_cycle",
        desc = 'FLOPS/cycle',
        x_label = 'FLOPS/cycle',
        value_col = 'CI_FLOPS_cycle',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix = "flops_cycle_pc",
        desc = r'FLOPS/cycle max [\%]',
        x_label = r'FLOPS/cycle max [\%]',
        value_col = 'flops_cycle_pc',
        bar_label = "{:.2%}",
        scale = "percentage",
    ),
    dict(
        suffix = "RENAME_renamedInsts",
        desc = 'Number of instructions processed by rename',
        x_label = 'Number of instructions processed by rename',
        value_col = 'RENAME_renamedInsts',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix  = "RENAME_renamedOperands",
        desc    = 'Number of destination operands rename has renamed',
        x_label = 'Number of destination operands rename has renamed',
        value_col = 'RENAME_renamedOperands',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix  = "RENAME_intLookups",
        desc    = 'Number of integer rename lookups',
        x_label = 'Number of integer rename lookups',
        value_col = 'RENAME_intLookups',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix  = "RENAME_vecLookups",
        desc    = 'Number of vector rename lookups',
        x_label = 'Number of vector rename lookups',
        value_col = 'RENAME_vecLookups',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "CPU_COMMIT_instsCommitted",
        desc    = 'Number of committed instructions',
        x_label = 'Number of committed instructions',
        value_col = 'CPU_COMMIT_instsCommitted',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "CPU_COMMIT_memRefs",
        desc    = 'Number of memory references committed',
        x_label = 'Number of memory references committed',
        value_col = 'CPU_COMMIT_memRefs',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "CPU_COMMIT_branches",
        desc    = 'Number of branches committed',
        x_label = 'Number of branches committed',
        value_col = 'CPU_COMMIT_branches',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "CPU_COMMIT_integer",
        desc    = 'Number of committed integer instructions',
        x_label = 'Number of committed integer instructions',
        value_col = 'CPU_COMMIT_integer',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "CPU_COMMIT_loads",
        desc    = 'Number of loads committed',
        x_label = 'Number of loads committed',
        value_col = 'CPU_COMMIT_loads',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "CPU_COMMIT_stores",
        desc    = 'Number of stores committed',
        x_label = 'Number of stores committed',
        value_col = 'CPU_COMMIT_stores',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "CPU_COMMIT_vectorInstructions",
        desc    = 'Number of committed Vector instructions',
        x_label = 'Number of committed Vector instructions',
        value_col = 'CPU_COMMIT_vectorInstructions',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "CPU_COMMIT_vector_loads",
        desc    = 'Number of committed vector loads',
        x_label = 'Number of committed vector loads',
        value_col = 'CPU_COMMIT_vector_loads',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "CPU_COMMIT_scalar_loads",
        desc    = 'Number of committed scalar loads',
        x_label = 'Number of committed scalar loads',
        value_col = 'CPU_COMMIT_scalar_loads',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "CPU_COMMIT_vector_stores",
        desc    = 'Number of committed vector stores',
        x_label = 'Number of committed vector stores',
        value_col = 'CPU_COMMIT_vector_stores',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "CPU_COMMIT_scalar_stores",
        desc    = 'Number of committed scalar stores',
        x_label = 'Number of committed scalar stores',
        value_col = 'CPU_COMMIT_scalar_stores',
        bar_label = "{:.2E}",
    ),

    dict(
        suffix = "CI_FP_Simd",
        desc    = 'Number of Vector FP instructions committed',
        x_label = 'Number of Vector FP instructions committed',
        value_col = 'CI_FP_Simd',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "CI_FP_Float",
        desc    = 'Number of Scalar FP instructions committed',
        x_label = 'Number of Scalar FP instructions committed',
        value_col = 'CI_FP_Float',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "CI_FP_SimdFloatAdd",
        desc    = 'Number of Vector FADD instructions committed',
        x_label = 'Number of Vector FADD instructions committed',
        value_col = 'CI_FP_SimdFloatAdd',
        bar_label = "{:.2E}",
    ),

    dict(
        suffix = "CI_FP_SimdFloatMult",
        desc    = 'Number of Vector FMUL instructions committed',
        x_label = 'Number of Vector FMUL instructions committed',
        value_col = 'CI_FP_SimdFloatMult',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "CI_FP_SimdFloatMultAcc",
        desc    = 'Number of Vector FMLA instructions committed',
        x_label = 'Number of Vector FMLA instructions committed',
        value_col = 'CI_FP_SimdFloatMultAcc',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "CI_FP_FloatAdd",
        desc    = 'Number of Scalar FADD instructions committed',
        x_label = 'Number of Scalar FADD instructions committed',
        value_col = 'CI_FP_FloatAdd',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "CI_FP_FloatMult",
        desc    = 'Number of Scalar FMUL instructions committed',
        x_label = 'Number of Scalar FMUL instructions committed',
        value_col = 'CI_FP_FloatMult',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "CI_FP_FloatMultAcc",
        desc    = 'Number of Scalar FMLA instructions committed',
        x_label = 'Number of Scalar FMLA instructions committed',
        value_col = 'CI_FP_FloatMultAcc',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "CI_Vector_ls",
        desc    = 'Number of vector accesses',
        x_label = 'Number of vector accesses',
        value_col = 'CI_Vector_ls',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "CI_Scalar_ls",
        desc    = 'Number of scalar accesses',
        x_label = 'Number of scalar accesses',
        value_col = 'CI_Scalar_ls',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "CI_Int_Alu",
        desc    = 'Number of committed Integer ALU instr.',
        x_label = 'Number of committed Integer ALU instr.',
        value_col = 'CI_Int_Alu',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "CI_Mem_Read",
        desc = 'Committed memory read instructions',
        x_label = 'Committed memory read instructions',
        value_col = 'CI_Mem_Read',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "CI_Mem_Write",
        desc = 'Committed memory write instructions',
        x_label = 'Committed memory write instructions',
        value_col = 'CI_Mem_Write',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "CI_Mem_Read_log",
        desc = 'Number of committed memory read instructions',
        x_label = 'Number of committed memory read instructions',
        value_col = 'CI_Mem_Read',
        bar_label = "{:.2E}",
        scale='log'
    ),
    dict(
        suffix = "CI_Mem_Write_log",
        desc = 'Number of committed memory write instructions',
        x_label = 'Number of committed memory write instructions',
        value_col = 'CI_Mem_Write',
        bar_label = "{:.2E}",
        scale='log'
    ),

    dict(
        suffix = "fetch_cycles_cpu",
        desc    = 'Number of cycles fetch has run',
        x_label = 'Number of cycles fetch has run',
        value_col = 'fetch_cycles_cpu',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "fetch_icacheStallCycles_cpu",
        desc    = 'Number of cycles fetch is stalled',
        x_label = 'Number of cycles fetch is stalled',
        value_col = 'fetch_icacheStallCycles_cpu',
        bar_label = "{:.2E}",
    ),

]

cache_plots = [
    dict(
        suffix = "dcache_accesses",
        desc = 'Number of Data Cache Accesses',
        x_label = 'Number of Data Cache Accesses',
        value_col = 'dcache_accesses',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "dcache_hits",
        desc = 'Number of Data Cache Hits',
        x_label = 'Number of Data Cache Hits',
        value_col = 'dcache_hits',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "dcache_misses",
        desc = 'Number of Data Cache Misses',
        x_label = 'Number of Data Cache Misses',
        value_col = 'dcache_misses',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "dcache_miss_rate",
        desc = r'Data Cache Miss Rate [\%]',
        x_label = r'Data Cache Miss Rate [\%]',
        value_col = 'dcache_miss_rate',
        bar_label = "{:.2%}",
        scale = "percentage",
    ),
     dict(
        suffix = "l2_demand_accesses",
        desc = 'Number of L2 Cache Demand Accesses',
        x_label = 'Number of L2 Cache Demand Accesses',
        value_col = 'l2_demand_accesses',
        bar_label = "{:.2E}",
    ),
     dict(
        suffix = "l2_demand_hits",
        desc = 'Number of L2 Cache Demand Hits',
        x_label = 'Number of L2 Cache Demand Hits',
        value_col = 'l2_demand_hits',
        bar_label = "{:.2E}",
    ),
     dict(
        suffix = "l2_demand_misses",
        desc = 'Number of L2 Cache Demand Misses',
        x_label = 'Number of L2 Cache Demand Misses',
        value_col = 'l2_demand_misses',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "l2_demand_miss_rate",
        desc = r'L2 Cache Demand Miss Rate [\%]',
        x_label = r'L2 Cache Demand Miss Rate [\%]',
        value_col = 'l2_demand_miss_rate',
        bar_label = "{:.2%}",
        scale = "percentage",
    ),
    dict(
        suffix = "l2_total_accesses",
        desc = 'L2 Cache Total Accesses',
        x_label = 'L2 Cache Total Accesses',
        value_col = 'l2_total_accesses',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "l2_total_hits",
        desc = 'L2 Cache Total Hits',
        x_label = 'L2 Cache Total Hits',
        value_col = 'l2_total_hits',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "l2_total_misses",
        desc = 'L2 Cache Total Misses',
        x_label = 'L2 Cache Total Misses',
        value_col = 'l2_total_misses',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "l2_total_miss_rate",
        desc = r'L2 Cache Total Miss Rate [\%]',
        x_label = r'L2 Cache Total Miss Rate [\%]',
        value_col = 'l2_total_miss_rate',
        bar_label = "{:.2%}",
        scale = "percentage",
    ),
    dict(
        suffix = "l2_prefetch_accesses",
        desc = 'L2 Cache Prefetch Accesses',
        x_label = 'L2 Cache Prefetch Accesses',
        value_col = 'l2_prefetch_accesses',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "l2_prefetch_hits",
        desc = 'L2 Cache Prefetch Hits',
        x_label = 'L2 Cache Prefetch Hits',
        value_col = 'l2_prefetch_hits',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "l2_prefetch_misses",
        desc = 'L2 Cache Prefetch Misses',
        x_label = 'L2 Cache Prefetch Misses',
        value_col = 'l2_prefetch_misses',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "l2_prefetch_miss_rate",
        desc = r'L2 Cache Prefetch Miss Rate [\%]',
        x_label = r'L2 Cache Prefetch Miss Rate [\%]',
        value_col = 'l2_prefetch_miss_rate',
        bar_label = "{:.2%}",
        scale = "percentage",
    ),
    dict(
        suffix = "l3_demand_accesses",
        desc = 'SLC Demand Accesses',
        x_label = 'SLC Demand Accesses',
        value_col = 'l3_demand_accesses',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "l3_demand_hits",
        desc = 'SLC Demand Hits',
        x_label = 'SLC Demand Hits',
        value_col = 'l3_demand_hits',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "l3_demand_misses",
        desc = 'SLC Demand Misses',
        x_label = 'SLC Demand Misses',
        value_col = 'l3_demand_misses',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "l3_demand_miss_rate",
        desc = 'SLC Demand Miss Rate',
        x_label = r'SLC Demand Miss Rate [\%]',
        value_col = 'l3_demand_miss_rate',
        bar_label = "{:.2%}",
        scale = "percentage",
    ),
    dict(
        suffix = "l3_total_accesses",
        desc = 'SLC Total Accesses',
        x_label = 'SLC Total Accesses',
        value_col = 'l3_total_accesses',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "l3_total_hits",
        desc = 'SLC Total Hits',
        x_label = 'SLC Total Hits',
        value_col = 'l3_total_hits',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "l3_total_misses",
        desc = 'SLC Total Misses',
        x_label = 'SLC Total Misses',
        value_col = 'l3_total_misses',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "l3_total_miss_rate",
        desc = 'SLC Total Miss Rate',
        x_label = r'SLC Total Miss Rate [\%]',
        value_col = 'l3_total_miss_rate',
        bar_label = "{:.2%}",
        scale = "percentage",
    ),
    dict(
        suffix = "l3_prefetch_accesses",
        desc = 'SLC Prefetch Accesses',
        x_label = 'SLC Prefetch Accesses',
        value_col = 'l3_prefetch_accesses',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "l3_prefetch_hits",
        desc = 'SLC Prefetch Hits',
        x_label = 'SLC Prefetch Hits',
        value_col = 'l3_prefetch_hits',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "l3_prefetch_misses",
        desc = 'SLC Prefetch Misses',
        x_label = 'SLC Prefetch Misses',
        value_col = 'l3_prefetch_misses',
        bar_label = "{:.2E}",
    ),
        dict(
        suffix = "l3_prefetch_miss_rate",
        desc = 'SLC Prefetch Miss Rate',
        x_label = r'SLC Prefetch Miss Rate [\%]',
        value_col = 'l3_prefetch_miss_rate',
        bar_label = "{:.2%}",
        scale = "percentage",
    ),

    dict(
        suffix = "dcache_datIn_stall_time",
        desc = 'Average L1D Data In stall time',
        x_label = 'Avg. L1D Data In stall time [cycles]',
        value_col = 'caches_l1d_datIn_avg_stall_time',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "dcache_datOut_stall_time",
        desc = 'Average L1D Data Out stall time',
        x_label = 'Avg. L1D Data Out stall time [cycles]',
        value_col = 'caches_l1d_datOut_avg_stall_time',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "dcache_reqOut_stall_time",
        desc = 'Average L1D Request Out stall time',
        x_label = 'Avg. L1D Request Out stall time [cycles]',
        value_col = 'caches_l1d_reqOut_avg_stall_time',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "dcache_rspIn_stall_time",
        desc = 'Average L1D Response In stall time',
        x_label = 'Avg. L1D Response In stall time [cycles]',
        value_col = 'caches_l1d_rspIn_avg_stall_time',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "dcache_rspOut_stall_time",
        desc = 'Average L1D Response Out stall time',
        x_label = 'Avg. L1D Response Out stall time [cycles]',
        value_col = 'caches_l1d_rspOut_avg_stall_time',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "dcache_snpIn_stall_time",
        desc = 'Average L1D Snoop In stall time',
        x_label = 'Avg. L1D Snoop In stall time [cycles]',
        value_col = 'caches_l1d_snpIn_avg_stall_time',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "dcache_snpRdy_stall_time",
        desc = 'Average L1D Snoop Ready stall time',
        x_label = 'Avg. L1D Snoop Ready stall time [cycles]',
        value_col = 'caches_l1d_snpRdy_avg_stall_time',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "icache_datIn_stall_time",
        desc = 'Average L1I Data In stall time',
        x_label = 'Avg. L1I Data In stall time [cycles]',
        value_col = 'caches_l1i_datIn_avg_stall_time',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "icache_reqOut_stall_time",
        desc = 'Average L1I Request Out stall time',
        x_label = 'Avg. L1I Request Out stall time [cycles]',
        value_col = 'caches_l1i_reqOut_avg_stall_time',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "icache_rspIn_stall_time",
        desc = 'Average L1I Response In stall time',
        x_label = 'Avg. L1I Response In stall time [cycles]',
        value_col = 'caches_l1i_rspIn_avg_stall_time',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "icache_rspOut_stall_time",
        desc = 'Average L1I Response Out stall time',
        x_label = 'Avg. L1I Response Out stall time [cycles]',
        value_col = 'caches_l1i_rspOut_avg_stall_time',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "icache_snpIn_stall_time",
        desc = 'Average L1I Snoop In stall time',
        x_label = 'Avg. L1I Snoop In stall time [cycles]',
        value_col = 'caches_l1i_snpIn_avg_stall_time',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "icache_snpRdy_stall_time",
        desc = 'Average L1I Snoop Ready stall time',
        x_label = 'Avg. L1I Snoop Ready stall time [cycles]',
        value_col = 'caches_l1i_snpRdy_avg_stall_time',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "l2_datIn_stall_time",
        desc = 'Average L2 Data In stall time',
        x_label = 'Avg. L2 Data In stall time [cycles]',
        value_col = 'caches_l2_datIn_avg_stall_time',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "l2_datOut_stall_time",
        desc = 'Average L2 Data Out stall time',
        x_label = 'Avg. L2 Data Out stall time [cycles]',
        value_col = 'caches_l2_datOut_avg_stall_time',
        bar_label = "{:.2E}",
    ),
]

memory_plots = [
    dict(
        suffix = "mem_bus_rw_utilization",
        desc = 'Memory Bus Utilization',
        x_label = r'Memory Bus Utilization [\%]',
        value_col = 'mem_bus_rw_util',
        bar_label = "{:.2%}",
        scale = "percentage"
    ),
    dict(
        suffix = "mem_ctrls_bytes_written",
        desc = 'Data written by memory controller',
        x_label = 'Memory Writes [bytes]',
        value_col = 'mem_ctrls_bytes_written',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "mem_ctrls_bytes_read",
        desc = 'Data read by memory controller',
        x_label = 'Memory Reads [bytes]',
        value_col = 'mem_ctrls_bytes_read',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "mem_ctrls_bytes_rw",
        desc = 'Data read+written by memory controller',
        x_label = 'Memory Reads+Writes [bytes]',
        value_col = 'mem_ctrls_bytes_rw',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "bw_gem5_GB",
        desc = 'Mem Bandwidth [GB/s]',
        x_label = 'Mem Bandwidth [GB/s]',
        value_col = 'bw_gem5_GB',
        bar_label = "{:.2f} GB/s",
    ),
]

mesh_plots = [
    dict(
        suffix = "mesh_total_hops_cycle",
        desc    = 'Total Mesh Hops / cycle',
        x_label = 'Total Mesh Hops / cycle',
        value_col = 'mesh_total_hops_cycle',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix = "mesh_flits_received_cycle",
        desc    = 'Mesh Flits Received / cycle',
        x_label = 'Mesh Flits Received / cycle',
        value_col = 'mesh_flits_received_cycle',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix = "mesh_average_hops",
        desc    = 'Average Mesh Hops',
        x_label = 'Average Mesh Hops',
        value_col = 'mesh_average_hops',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix = "mesh_total_hops",
        desc    = 'Total Mesh Hops',
        x_label = 'Total Mesh Hops',
        value_col = 'mesh_total_hops',
        bar_label = "{:.2E}",
    ),

    dict(
        suffix    = "mesh_avg_flit_latency_network_vnet0",
        value_col = 'mesh_avg_flit_latency_network_vnet0',
        x_label   = 'VNET=0 Average Flit Network Latency [cycles]',
        desc      = 'VNET=0 Average Flit Network Latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = "mesh_avg_flit_latency_network_vnet1",
        value_col = 'mesh_avg_flit_latency_network_vnet1',
        x_label   = 'VNET=1 Average Flit Network Latency [cycles]',
        desc      = 'VNET=1 Average Flit Network Latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = "mesh_avg_flit_latency_network_vnet2",
        value_col = 'mesh_avg_flit_latency_network_vnet2',
        x_label   = 'VNET=2 Average Flit Network Latency [cycles]',
        desc      = 'VNET=2 Average Flit Network Latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = "mesh_avg_flit_latency_network_vnet3",
        value_col = 'mesh_avg_flit_latency_network_vnet3',
        x_label   = 'VNET=3 Average Flit Network Latency [cycles]',
        desc      = 'VNET=3 Average Flit Network Latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = "mesh_avg_flit_latency_network",
        value_col = 'mesh_avg_flit_latency_network',
        x_label   = 'Average Flit Network Latency [cycles]',
        desc      = 'Average Flit Network Latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = "mesh_avg_flit_latency_queueing_vnet0",
        value_col = 'mesh_avg_flit_latency_queueing_vnet0',
        x_label   = 'VNET=0 Average Flit Queueing Latency [cycles]',
        desc      = 'VNET=0 Average Flit Queueing Latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = "mesh_avg_flit_latency_queueing_vnet1",
        value_col = 'mesh_avg_flit_latency_queueing_vnet1',
        x_label   = 'VNET=1 Average Flit Queueing Latency [cycles]',
        desc      = 'VNET=1 Average Flit Queueing Latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = "mesh_avg_flit_latency_queueing_vnet2",
        value_col = 'mesh_avg_flit_latency_queueing_vnet2',
        x_label   = 'VNET=2 Average Flit Queueing Latency [cycles]',
        desc      = 'VNET=2 Average Flit Queueing Latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = "mesh_avg_flit_latency_queueing_vnet3",
        value_col = 'mesh_avg_flit_latency_queueing_vnet3',
        x_label   = 'VNET=3 Average Flit Queueing Latency [cycles]',
        desc      = 'VNET=3 Average Flit Queueing Latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = "mesh_avg_flit_latency_queueing",
        value_col = 'mesh_avg_flit_latency_queueing',
        x_label   = 'Average Flit Queueing Latency [cycles]',
        desc      = 'Average Flit Queueing Latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = "mesh_avg_flit_latency_total_vnet0",
        value_col = 'mesh_avg_flit_latency_total_vnet0',
        x_label   = 'VNET=0 Average Flit Total Latency [cycles]',
        desc      = 'VNET=0 Average Flit Total Latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = "mesh_avg_flit_latency_total_vnet1",
        value_col = 'mesh_avg_flit_latency_total_vnet1',
        x_label   = 'VNET=1 Average Flit Total Latency [cycles]',
        desc      = 'VNET=1 Average Flit Total Latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = "mesh_avg_flit_latency_total_vnet2",
        value_col = 'mesh_avg_flit_latency_total_vnet2',
        x_label   = 'VNET=2 Average Flit Total Latency [cycles]',
        desc      = 'VNET=2 Average Flit Total Latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = "mesh_avg_flit_latency_total_vnet3",
        value_col = 'mesh_avg_flit_latency_total_vnet3',
        x_label   = 'VNET=3 Average Flit Total Latency [cycles]',
        desc      = 'VNET=3 Average Flit Total Latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = "mesh_avg_flit_latency_total",
        value_col = 'mesh_avg_flit_latency_total',
        x_label   = 'Average Flit Total Latency [cycles]',
        desc      = 'Average Flit Total Latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix = "mesh_flits_received_total",
        value_col = 'mesh_flits_received_total',
        desc = 'Total Flits Received',
        x_label = 'Total Flits Received',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "mesh_flits_received_vnet0",
        value_col = 'mesh_flits_received_vnet0',
        desc = 'VNET0 Flits Received',
        x_label = 'VNET0 Flits Received',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "mesh_flits_received_vnet1",
        value_col = 'mesh_flits_received_vnet1',
        desc = 'VNET1 Flits Received',
        x_label = 'VNET1 Flits Received',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "mesh_flits_received_vnet2",
        value_col = 'mesh_flits_received_vnet2',
        desc = 'VNET2 Flits Received',
        x_label = 'VNET2 Flits Received',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "mesh_flits_received_vnet3",
        value_col = 'mesh_flits_received_vnet3',
        desc = 'VNET3 Flits Received',
        x_label = 'VNET3 Flits Received',
        bar_label = "{:.2E}",
    ),
]




network_plots = [
    dict(
        suffix = "network_total_hops_cycle",
        desc    = 'Total Network Hops / cycle',
        x_label = 'Total Network Hops / cycle',
        value_col = 'network_total_hops_cycle',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix = "network_flits_received_cycle",
        desc    = 'Total Packets Received / cycle',
        x_label = 'Total Packets Received / cycle',
        value_col = 'network_flits_received_cycle',
        bar_label = "{:.2f}",
    ),  
    dict(
        suffix = "avg_packet_latency",
        desc = 'Average packet total latency',
        x_label = 'Avg. total latency [cycles]',
        value_col = 'network_avg_packet_latency',
    ),
    dict(
        suffix = "avg_packet_net_latency",
        desc = 'Average packet network latency',
        x_label = 'Avg. network latency [cycles]',
        value_col = 'network_avg_packet_latency_network',
    ),
    dict(
        suffix = "avg_packet_queue_latency",
        desc = 'Average packet queueing latency',
        x_label = 'Avg. queueing latency [cycles]',
        value_col = 'network_avg_packet_latency_queueing',
    ),
    dict(
        suffix    = 'network_avg_packet_latency_vnet0',
        value_col = 'network_avg_packet_latency_vnet0',
        desc    = 'Average VNET0 packet latency',
        x_label = 'Average VNET0 packet latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = 'network_avg_packet_latency_vnet1',
        value_col = 'network_avg_packet_latency_vnet1',
        desc    = 'Average VNET1 packet latency',
        x_label = 'Average VNET1 packet latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = 'network_avg_packet_latency_vnet2',
        value_col = 'network_avg_packet_latency_vnet2',
        desc    = 'Average VNET2 packet latency',
        x_label = 'Average VNET2 packet latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = 'network_avg_packet_latency_vnet3',
        value_col = 'network_avg_packet_latency_vnet3',
        desc    = 'Average VNET3 packet latency',
        x_label = 'Average VNET3 packet latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = 'network_avg_packet_latency_network_vnet0',
        value_col = 'network_avg_packet_latency_network_vnet0',
        desc    = 'Average VNET0 network latency',
        x_label = 'Avg. VNET0 network latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = 'network_avg_packet_latency_network_vnet1',
        value_col = 'network_avg_packet_latency_network_vnet1',
        desc    = 'Average VNET1 network latency',
        x_label = 'Avg. VNET1 network latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = 'network_avg_packet_latency_network_vnet2',
        value_col = 'network_avg_packet_latency_network_vnet2',
        desc    = 'Average VNET2 network latency',
        x_label = 'Avg. VNET2 network latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = 'network_avg_packet_latency_network_vnet3',
        value_col = 'network_avg_packet_latency_network_vnet3',
        desc    = 'Average VNET3 network latency',
        x_label = 'Avg. VNET3 network latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = 'network_avg_packet_latency_queueing_vnet0',
        value_col = 'network_avg_packet_latency_queueing_vnet0',
        desc    = 'Average VNET0 queueing latency',
        x_label = 'Avg. VNET0 queueing latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = 'network_avg_packet_latency_queueing_vnet1',
        value_col = 'network_avg_packet_latency_queueing_vnet1',
        desc    = 'Average VNET1 queueing latency',
        x_label = 'Avg. VNET1 queueing latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = 'network_avg_packet_latency_queueing_vnet2',
        value_col = 'network_avg_packet_latency_queueing_vnet2',
        desc    = 'Average VNET2 queueing latency',
        x_label = 'Avg. VNET2 queueing latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = 'network_avg_packet_latency_queueing_vnet3',
        value_col = 'network_avg_packet_latency_queueing_vnet3',
        desc    = 'Average VNET3 queueing latency',
        x_label = 'Avg. VNET3 queueing latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix = "network_average_hops",
        desc = 'Average Network Packet Hops (Total Hops / Total Packets)',
        x_label = 'Avg. Network Packet Hops',
        value_col = 'network_average_hops',
    ),
    dict(
        suffix = "network_avg_link_utilization",
        desc = 'Average Network Link Utilization (Activity / Time)',
        x_label = 'Avg. Total Network Link Utilization [link/cycle]',
        value_col = 'network_avg_link_utilization',
    ),
    dict(
        suffix = "network_avg_int_link_util",
        desc = 'Average Internal Link Utilization (Activity / Time)',
        x_label = 'Avg. Internal Link Utilization [link/cycle]',
        value_col = 'network_avg_int_link_util',
    ),
    dict(
        suffix = "network_avg_ext_link_util",
        desc = 'Average External Link Utilization (Activity / Time)',
        x_label = 'Avg. External Link Utilization [link/cycle]',
        value_col = 'network_avg_ext_link_util',
    ),
    dict(
        suffix = "network_avg_ext_in_link_util",
        desc = 'Average External-In Link Utilization (Activity / Time)',
        x_label = 'Avg. External-In Link Utilization [link/cycle]',
        value_col = 'network_avg_ext_in_link_util',
    ),
    dict(
        suffix = "network_avg_ext_out_link_util",
        desc = 'Average External-Out Link Utilization (Activity / Time)',
        x_label = 'Avg. External-Out Link Utilization [link/cycle]',
        value_col = 'network_avg_ext_out_link_util',
    ),
    dict(
        suffix = "network_flits_injected_total",
        desc = 'Total Flits Injected',
        x_label = 'Total Flits Injected',
        value_col = 'network_flits_injected_total',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix = "network_flits_received_total",
        desc = 'Total Packets Received',
        x_label = 'Total Packets Received',
        value_col = 'network_flits_received_total',
        bar_label = "{:.2E}",
    ),

    dict(
        suffix    = "network_routers_vnet0_src_dst_total_packets_all",
        value_col = 'network_routers_vnet0_src_dst_total_packets_all',
        desc =    'VNET0 total packet traffic',
        x_label = 'VNET0 total packet traffic',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix    = "network_routers_vnet0_src_dst_total_packets_ext",
        value_col = 'network_routers_vnet0_src_dst_total_packets_ext',
        desc    = r'VNET0 packet traffic (NOC)',
        x_label = r'VNET0 packet traffic (NOC)',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix    = "network_routers_vnet0_src_dst_total_packets_int",
        value_col = 'network_routers_vnet0_src_dst_total_packets_int',
        desc    = r'VNET0 packet traffic (private)',
        x_label = r'VNET0 packet traffic (private)',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix    = "network_routers_vnet0_src_dst_total_packets_ext_pc",
        value_col = 'network_routers_vnet0_src_dst_total_packets_ext_pc',
        desc    = r'VNET0 packet traffic (NOC) [\% total]',
        x_label = r'VNET0 packet traffic (NOC) [\% total]',
        bar_label = "{:.2%}",
        scale = "percentage",
    ),
    dict(
        suffix    = "network_routers_vnet0_src_dst_total_packets_int_pc",
        value_col = 'network_routers_vnet0_src_dst_total_packets_int_pc',
        desc    = r'VNET0 packet traffic (private) [\% total]',
        x_label = r'VNET0 packet traffic (private) [\% total]',
        bar_label = "{:.2%}",
        scale = "percentage",
    ),
    dict(
        suffix    = "network_routers_vnet1_src_dst_total_packets_all",
        value_col = 'network_routers_vnet1_src_dst_total_packets_all',
        desc =    'VNET1 total packet traffic',
        x_label = 'VNET1 total packet traffic',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix    = "network_routers_vnet1_src_dst_total_packets_ext",
        value_col = 'network_routers_vnet1_src_dst_total_packets_ext',
        desc    = r'VNET1 packet traffic (NOC)',
        x_label = r'VNET1 packet traffic (NOC)',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix    = "network_routers_vnet1_src_dst_total_packets_int",
        value_col = 'network_routers_vnet1_src_dst_total_packets_int',
        desc    = r'VNET1 packet traffic (private)',
        x_label = r'VNET1 packet traffic (private)',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix    = "network_routers_vnet1_src_dst_total_packets_ext_pc",
        value_col = 'network_routers_vnet1_src_dst_total_packets_ext_pc',
        desc    = r'VNET1 packet traffic (NOC) [\% total]',
        x_label = r'VNET1 packet traffic (NOC) [\% total]',
        bar_label = "{:.2%}",
        scale = "percentage",
    ),
    dict(
        suffix    = "network_routers_vnet1_src_dst_total_packets_int_pc",
        value_col = 'network_routers_vnet1_src_dst_total_packets_int_pc',
        desc    = r'VNET1 packet traffic (private) [\% total]',
        x_label = r'VNET1 packet traffic (private) [\% total]',
        bar_label = "{:.2%}",
        scale = "percentage",
    ),
    dict(
        suffix    = "network_routers_vnet2_src_dst_total_packets_all",
        value_col = 'network_routers_vnet2_src_dst_total_packets_all',
        desc =    'VNET2 total packet traffic',
        x_label = 'VNET2 total packet traffic',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix    = "network_routers_vnet2_src_dst_total_packets_ext",
        value_col = 'network_routers_vnet2_src_dst_total_packets_ext',
        desc    = r'VNET2 packet traffic (NOC)',
        x_label = r'VNET2 packet traffic (NOC)',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix    = "network_routers_vnet2_src_dst_total_packets_int",
        value_col = 'network_routers_vnet2_src_dst_total_packets_int',
        desc    = r'VNET2 packet traffic (private)',
        x_label = r'VNET2 packet traffic (private)',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix    = "network_routers_vnet2_src_dst_total_packets_ext_pc",
        value_col = 'network_routers_vnet2_src_dst_total_packets_ext_pc',
        desc    = r'VNET2 packet traffic (NOC) [\% total]',
        x_label = r'VNET2 packet traffic (NOC) [\% total]',
        bar_label = "{:.2%}",
        scale = "percentage",
    ),
    dict(
        suffix    = "network_routers_vnet2_src_dst_total_packets_int_pc",
        value_col = 'network_routers_vnet2_src_dst_total_packets_int_pc',
        desc    = r'VNET2 packet traffic (private) [\% total]',
        x_label = r'VNET2 packet traffic (private) [\% total]',
        bar_label = "{:.2%}",
        scale = "percentage",
    ),
    dict(
        suffix    = "network_routers_vnet3_src_dst_total_packets_all",
        value_col = 'network_routers_vnet3_src_dst_total_packets_all',
        desc =    'VNET3 total packet traffic',
        x_label = 'VNET3 total packet traffic',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix    = "network_routers_vnet3_src_dst_total_packets_ext",
        value_col = 'network_routers_vnet3_src_dst_total_packets_ext',
        desc    = r'VNET3 packet traffic (NOC)',
        x_label = r'VNET3 packet traffic (NOC)',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix    = "network_routers_vnet3_src_dst_total_packets_int",
        value_col = 'network_routers_vnet3_src_dst_total_packets_int',
        desc    = r'VNET3 packet traffic (private)',
        x_label = r'VNET3 packet traffic (private)',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix    = "network_routers_vnet3_src_dst_total_packets_ext_pc",
        value_col = 'network_routers_vnet3_src_dst_total_packets_ext_pc',
        desc    = r'VNET3 packet traffic (NOC) [\% total]',
        x_label = r'VNET3 packet traffic (NOC) [\% total]',
        bar_label = "{:.2%}",
        scale = "percentage",
    ),
    dict(
        suffix    = "network_routers_vnet3_src_dst_total_packets_int_pc",
        value_col = 'network_routers_vnet3_src_dst_total_packets_int_pc',
        desc    = r'VNET3 packet traffic (private) [\% total]',
        x_label = r'VNET3 packet traffic (private) [\% total]',
        bar_label = "{:.2%}",
        scale = "percentage",
    ),
]

#     dict(
#        suffix = "cpu_pf_l2_accesses",
#        desc = 'Number of L2 Prefetcher Accesses',
#        x_label = 'Number of L2 Prefetcher Accesses',
#        value_col = 'cpu_pfl2_accesses',
#        bar_label = "{:.2E}",
#    ),
#     dict(
#        suffix = "cpu_pf_l2_Issued",
#        desc = 'Number of L2 Prefetcher Issued',
#        x_label = 'Number of L2 Prefetcher Issued',
#        value_col = 'cpu_pfl2_Issued',
#        bar_label = "{:.2E}",
#    ),

default_plots = [
    *time_plots,
    *memory_plots,
    *cpu_plots,
    *cache_plots,
    *mesh_plots,
    *network_plots,
]

combined_plots = [
    dict(
        suffix    = "mesh_avg_flit_latency_network_all_vnets",
        outer_value_cols = [
            ("VNET0", 'mesh_avg_flit_latency_network_vnet0'),
            ("VNET1", 'mesh_avg_flit_latency_network_vnet1'),
            ("VNET2", 'mesh_avg_flit_latency_network_vnet2'),
            ("VNET3", 'mesh_avg_flit_latency_network_vnet3'),
        ],
        #y_label = 'Protocol VNETs',
        x_label   = 'Average Network Latency [cycles]',
        desc      = 'Average Network Latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = "mesh_avg_flit_latency_network_all_vnets_log",
        outer_value_cols = [
            ("VNET0", 'mesh_avg_flit_latency_network_vnet0'),
            ("VNET1", 'mesh_avg_flit_latency_network_vnet1'),
            ("VNET2", 'mesh_avg_flit_latency_network_vnet2'),
            ("VNET3", 'mesh_avg_flit_latency_network_vnet3'),
        ],
        #y_label = 'Protocol VNETs',
        x_label   = 'Average Network Latency [cycles]',
        desc      = 'Average Network Latency [cycles]',
        bar_label = "{:.2f}",
        scale     = 'log',
        #label_x_delta = 2,
    ),
    dict(
        suffix    = "mesh_avg_flit_latency_queueing_all_vnets",
        outer_value_cols = [
            ("VNET0", 'mesh_avg_flit_latency_queueing_vnet0'),
            ("VNET1", 'mesh_avg_flit_latency_queueing_vnet1'),
            ("VNET2", 'mesh_avg_flit_latency_queueing_vnet2'),
            ("VNET3", 'mesh_avg_flit_latency_queueing_vnet3'),
        ],
        #y_label = 'Protocol VNETs',
        x_label   = 'Average Queueing Latency [cycles]',
        desc      = 'Average Queueing Latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = "mesh_avg_flit_latency_queueing_all_vnets_log",
        outer_value_cols = [
            ("VNET0", 'mesh_avg_flit_latency_queueing_vnet0'),
            ("VNET1", 'mesh_avg_flit_latency_queueing_vnet1'),
            ("VNET2", 'mesh_avg_flit_latency_queueing_vnet2'),
            ("VNET3", 'mesh_avg_flit_latency_queueing_vnet3'),
        ],
        #y_label = 'Protocol VNETs',
        x_label   = 'Average Queueing Latency [cycles]',
        desc      = 'Average Queueing Latency [cycles]',
        bar_label = "{:.2f}",
        scale     = 'log',
        #label_x_delta = 2,
    ),
    dict(
        suffix    = "mesh_avg_flit_latency_total_all_vnets",
        outer_value_cols = [
            ("VNET0", 'mesh_avg_flit_latency_total_vnet0'),
            ("VNET1", 'mesh_avg_flit_latency_total_vnet1'),
            ("VNET2", 'mesh_avg_flit_latency_total_vnet2'),
            ("VNET3", 'mesh_avg_flit_latency_total_vnet3'),
        ],
        #y_label = 'Protocol VNETs',
        x_label   = 'Average Total Latency [cycles]',
        desc      = 'Average Total Latency [cycles]',
        bar_label = "{:.2f}",
    ),
    dict(
        suffix    = "mesh_flits_received_all_vnets",
        outer_value_cols = [
            ("VNET0", 'mesh_flits_received_vnet0'),
            ("VNET1", 'mesh_flits_received_vnet1'),
            ("VNET2", 'mesh_flits_received_vnet2'),
            ("VNET3", 'mesh_flits_received_vnet3'),
        ],
        #y_label = 'Protocol VNETs',
        x_label   = 'Total Flits Received',
        desc      = 'Total Flits Received',
        bar_label = "{:.2E}",
    ),
    dict(
        suffix    = "mesh_flits_received_all_vnets_log",
        outer_value_cols = [
            ("VNET0", 'mesh_flits_received_vnet0'),
            ("VNET1", 'mesh_flits_received_vnet1'),
            ("VNET2", 'mesh_flits_received_vnet2'),
            ("VNET3", 'mesh_flits_received_vnet3'),
        ],
        #y_label = 'Protocol VNETs',
        x_label   = 'Total Flits Received',
        desc      = 'Total Flits Received',
        bar_label = "{:.2E}",
        scale = "log",
    ),
]