model: Simple2D
parameters:
  num_mesh_routers: 6
  router_numa_ids: [0,0,0,0,0,0]
  cpu_routers: [[1,4]]
  slc_routers: [[1,4]]
  mem_routers: [[0,3]]
  rom_routers: [2]
  dma_routers: [2]
  internal_links:
    - [0, 1, 1]
    - [1, 2, 1]
    - [3, 4, 1]
    - [4, 5, 1]
    - [0, 3, 2]
    - [1, 4, 2]
    - [2, 5, 2]
