#!/bin/bash

SRCDIR=$PACKER_PROVISION_SRCDIR
BLDDIR=$PACKER_PROVISION_BLDDIR
OUTDIR=$PACKER_PROVISION_OUTDIR
BENCHD=$PACKER_PROVISION_INSTALL

mkdir -p $SRCDIR $BLDDIR $OUTDIR $BENCHD

for P in $PACKER_PACKAGE_LIST; do
  pushd $PACKER_PROVISION_PKGDIR/$P
  SRCDIR=$SRCDIR BLDDIR=$BLDDIR OUTDIR=$OUTDIR BENCHD=$BENCHD bash -c ./install.sh
  popd
done

